
CREATE TABLE HEADER_TBL
(BLOCK_HEIGHT  		BIGINT          UNSIGNED NOT NULL,
BLOCK_HASH    		CHAR    (30)       	     NOT NULL,
TOTAL_OUTPUT  		DECIMAL (65, 2) UNSIGNED NOT NULL,
TOTAL_FEES    		DECIMAL (65, 2) UNSIGNED NOT NULL,
PREVIOUS_BLOCK_HASH CHAR    (30)     	     NOT NULL,
MERKLE_ROOT 		CHAR    (30)     	     NOT NULL,
NONCE 				BIGINT          UNSIGNED NOT NULL,
TIME_STAMP 			VARCHAR (30)   		     NOT NULL,
UNIQUE (BLOCK_REF),
UNIQUE (BLOCK_HASH),
UNIQUE (PREVIOUS_BLOCK_HASH),
UNIQUE (MERKLE_ROOT),
UNIQUE (TIME_STAMP));

CREATE TABLE UTXO_TBL
(TXID    	  		CHAR    (30)  	         NOT NULL,
BLOCK_REF  			BIGINT          UNSIGNED NOT NULL,
PUBLIC_KEY    		CHAR    (30)  	         NOT NULL, 
OUTPUT_VALUE  		DECIMAL (65,2)           NOT NULL,
CONSTRAINT UTXO_BLOCK_REF_FK FOREIGN KEY (BLOCK_REF) REFERENCES HEADER_TBL (BLOCK_HEIGHT));