CREATE TABLE TRANSACTION
(TXID    	  CHAR (30)  NOT NULL,
BLOCK_HEIGHT  INT UNSIGNED NOT NULL,
PUBLIC_KEY    VARCHAR (30)  NOT NULL, 
VALUE         DECIMAL (6,2) NULL);


CREATE TABLE BLOCK
(BLOCK_HEIGHT BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
BLOCK_DATA    MEDIUMBLOB NOT NULL;


CREATE TABLE HEADER
(BLOCK_HEIGHT  BIGINT UNSIGNED NOT NULL,
BLOCK_HASH    		CHAR (30) NOT NULL,
TOTAL_OUTPUT  		VARCHAR (2) NOT NULL,
TOTAL_FEES    		VARCHAR (2) NOT NULL,
PREVIOUS_BLOCK_HASH VARCHAR (2) NOT NULL,
MERKLE_ROOT 		VARCHAR (2) NOT NULL,
NONCE 				VARCHAR (2) NOT NULL,
TIME_STAMP 			DATETIME (2) NOT NULL);

CREATE TABLE UTXO_POOL
(BLOCK_HEIGHT VARCHAR (2) NOT NULL,
 					VARCHAR (2) NOT NULL);